### ISSUE TITLE
Basic setup for serialization-testing

### ISSUE THREAD

**Issue by Byron** [serde-rs/yaml#1]
Consider using the existing pure-python implementation as reference for the desired output.

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/50znbo629ko).

*`serde-yaml #2 [some project planning]`*

[\![thumb](https://i.ytimg.com/vi/50znbo629ko/mqdefault.jpg)](https://youtu.be/50znbo629ko)

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/4UC7IQl6tUQ).

*`serde-yaml #3 [move into organization repository]`*

[\![thumb](https://i.ytimg.com/vi/4UC7IQl6tUQ/mqdefault.jpg)](https://youtu.be/4UC7IQl6tUQ)

**Comment by Byron** [comment]
test

**Comment by oli-obk** [comment]
funky :D are these automatically posted? what software are you using

**Comment by Byron** [comment]
Yes they are, even though it has a hickup right now that I am trying to fix (sorry for the spam :)). I am using [this program](http://nodegh.io/) to do the job.

**Comment by Byron** [comment]
Oh, and here is the script that usually does it: https://github.com/Byron/depot/blob/master/src/bash/upload-session-to-youtube.bash
