### ISSUE TITLE
Another YAML in Rust Project: Yaml-rust

### ISSUE THREAD

**Issue by killercup** [serde-rs/yaml#5]
Hi, I just saw https://users.rust-lang.org/t/yaml-rust-the-missing-yaml-1-2-parser-for-pure-rust/1659 and thought you might be interested in that.

If I understand correctly, it's a YAML 1.2 parser written in Rust that deals with complete documents, i.e. it doesn't use a streaming approach like this parser (it's not based on serde).

---

This is of course not an actionable issue per se, I just wanted to let you know and maybe start a discussion/the grand code copy event of 2015! :)

**Comment by Byron** [comment]
Thanks a lot for the hint ! Just took a thorough look at it, and came to believe that this project will totally help my work here, as I will now have a very nice reference of something that is working already.

The video will take a while to upload, but will be added here tomorrow.

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/a0PTR_n90Ro).

*`serde-yaml #34 [looking into yaml-rust]`*

[\![thumb](https://i.ytimg.com/vi/a0PTR_n90Ro/mqdefault.jpg)](https://youtu.be/a0PTR_n90Ro)
